// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyProject.Data;

#nullable disable

namespace MyProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506114747_AddMoreProducts")]
    partial class AddMoreProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyProject.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Luxury and premium watches for men",
                            Name = "Men's Watches"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Elegant and stylish watches for women",
                            Name = "Women's Watches"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Matching watch pairs for couples",
                            Name = "Couple Watches"
                        });
                });

            modelBuilder.Entity("MyProject.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("MyProject.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("MyProject.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("GalleryImages")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Citizen Eco-Drive men's watch, light-powered battery",
                            Discount = 10m,
                            GalleryImages = "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&q=80,https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=600&q=80,https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&q=80",
                            IsActive = true,
                            Name = "Citizen Eco-Drive",
                            Price = 4500000m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Seiko 5 men's watch, automatic movement",
                            Discount = 5m,
                            GalleryImages = "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600&q=80,https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=600&q=80,https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600&q=80",
                            IsActive = true,
                            Name = "Seiko 5",
                            Price = 3800000m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Casio Sheen women's watch, sapphire crystal",
                            Discount = 0m,
                            GalleryImages = "https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=600&q=80,https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600&q=80,https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=600&q=80",
                            IsActive = true,
                            Name = "Casio Sheen",
                            Price = 2900000m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Olym Pianus couple watch set, premium leather strap",
                            Discount = 15m,
                            GalleryImages = "https://images.unsplash.com/photo-1548171915-e79a380a2a4b?w=600&q=80,https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&q=80,https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1548171915-e79a380a2a4b?w=600&q=80",
                            IsActive = true,
                            Name = "Olym Pianus Couple Set",
                            Price = 8500000m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tissot PRX men's watch, automatic, elegant design",
                            Discount = 0m,
                            GalleryImages = "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=600&q=80,https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&q=80,https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=600&q=80",
                            IsActive = true,
                            Name = "Tissot PRX",
                            Price = 12500000m,
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Orient Bambino men's watch, sapphire crystal, leather strap",
                            Discount = 8m,
                            GalleryImages = "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&q=80,https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&q=80,https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&q=80",
                            IsActive = true,
                            Name = "Orient Bambino",
                            Price = 5500000m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Daniel Wellington women's watch, minimalist design, NATO strap",
                            Discount = 20m,
                            GalleryImages = "https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=600&q=80,https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=600&q=80,https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=600&q=80",
                            IsActive = true,
                            Name = "Daniel Wellington",
                            Price = 6200000m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Longines Master Collection, automatic chronograph",
                            Discount = 0m,
                            GalleryImages = "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=600&q=80,https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&q=80,https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=600&q=80",
                            IsActive = true,
                            Name = "Longines Master Collection",
                            Price = 22000000m,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fossil Jacqueline women's watch, elegant round dial",
                            Discount = 25m,
                            GalleryImages = "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&q=80,https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=600&q=80,https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&q=80",
                            IsActive = true,
                            Name = "Fossil Jacqueline",
                            Price = 3200000m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Seiko couple watch set, perfectly matching design",
                            Discount = 10m,
                            GalleryImages = "https://images.unsplash.com/photo-1548171915-e79a380a2a4b?w=600&q=80,https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&q=80,https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1548171915-e79a380a2a4b?w=600&q=80",
                            IsActive = true,
                            Name = "Seiko Couple Set",
                            Price = 9800000m,
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hamilton Khaki Field watch, automatic, 100m water resistant",
                            Discount = 5m,
                            GalleryImages = "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600&q=80,https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=600&q=80,https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600&q=80",
                            IsActive = true,
                            Name = "Hamilton Khaki Field",
                            Price = 16000000m,
                            StockQuantity = 7
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Skagen Signatur women's watch, Danish minimalism",
                            Discount = 0m,
                            GalleryImages = "https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=600&q=80,https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=600&q=80,https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=600&q=80",
                            IsActive = true,
                            Name = "Skagen Signatur",
                            Price = 2800000m,
                            StockQuantity = 22
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Omega Seamaster, iconic dive watch, sapphire crystal",
                            Discount = 0m,
                            GalleryImages = "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&q=80,https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=600&q=80,https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&q=80",
                            IsActive = true,
                            Name = "Omega Seamaster",
                            Price = 45000000m,
                            StockQuantity = 3
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Citizen Eco-Drive couple watch set, light-powered",
                            Discount = 15m,
                            GalleryImages = "https://images.unsplash.com/photo-1548171915-e79a380a2a4b?w=600&q=80,https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&q=80,https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1548171915-e79a380a2a4b?w=600&q=80",
                            IsActive = true,
                            Name = "Citizen Couple Set",
                            Price = 7200000m,
                            StockQuantity = 14
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Casio Edifice men's watch, Tough Solar, sapphire crystal",
                            Discount = 0m,
                            GalleryImages = "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&q=80,https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&q=80,https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&q=80",
                            IsActive = true,
                            Name = "Casio Edifice",
                            Price = 4800000m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cluse Minuit women's watch, French elegance, interchangeable strap",
                            Discount = 30m,
                            GalleryImages = "https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=600&q=80,https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=600&q=80,https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=600&q=80",
                            IsActive = true,
                            Name = "Cluse Minuit",
                            Price = 2500000m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tag Heuer Monaco, iconic square case, automatic chronograph",
                            Discount = 0m,
                            GalleryImages = "https://images.unsplash.com/photo-1619134778706-7015533a6150?w=600&q=80,https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=600&q=80,https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1619134778706-7015533a6150?w=600&q=80",
                            IsActive = true,
                            Name = "Tag Heuer Monaco",
                            Price = 52000000m,
                            StockQuantity = 4
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bulova Precisionist, ultra-precise quartz movement, sapphire crystal",
                            Discount = 10m,
                            GalleryImages = "https://images.unsplash.com/photo-1622434641406-a158123450f9?w=600&q=80,https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600&q=80,https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1622434641406-a158123450f9?w=600&q=80",
                            IsActive = true,
                            Name = "Bulova Precisionist",
                            Price = 7800000m,
                            StockQuantity = 16
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Frederique Constant Classics, elegant dress watch, automatic movement",
                            Discount = 5m,
                            GalleryImages = "https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=600&q=80,https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=600&q=80,https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=600&q=80",
                            IsActive = true,
                            Name = "Frederique Constant Classics",
                            Price = 18500000m,
                            StockQuantity = 6
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Baume et Mercier Classima, ladies elegant dress watch, quartz",
                            Discount = 0m,
                            GalleryImages = "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=600&q=80,https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=600&q=80,https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=600&q=80",
                            IsActive = true,
                            Name = "Baume et Mercier Classima",
                            Price = 12800000m,
                            StockQuantity = 9
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tissot Chemises, classic ladies watch, sapphire crystal",
                            Discount = 15m,
                            GalleryImages = "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=600&q=80,https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=600&q=80,https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=600&q=80",
                            IsActive = true,
                            Name = "Tissot Chemises",
                            Price = 5600000m,
                            StockQuantity = 21
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Longines DolceVita, ladies luxury watch, rectangular case, automatic",
                            Discount = 0m,
                            GalleryImages = "https://images.unsplash.com/photo-1619134778706-7015533a6150?w=600&q=80,https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=600&q=80,https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1619134778706-7015533a6150?w=600&q=80",
                            IsActive = true,
                            Name = "Longines DolceVita",
                            Price = 17000000m,
                            StockQuantity = 7
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cartier Santos de Cartier, legendary aviator watch, steel bracelet",
                            Discount = 0m,
                            GalleryImages = "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&q=80,https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=600&q=80,https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&q=80",
                            IsActive = true,
                            Name = "Cartier Santos de Cartier",
                            Price = 62000000m,
                            StockQuantity = 2
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Seiko Prospex Turtle, legendary dive watch, automatic, 200m water resistant",
                            Discount = 0m,
                            GalleryImages = "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&q=80,https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600&q=80,https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&q=80",
                            IsActive = true,
                            Name = "Seiko Prospex Turtle",
                            Price = 8200000m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Omega De Ville Prestige, ladies luxury watch, Co-Axial movement",
                            Discount = 0m,
                            GalleryImages = "https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=600&q=80,https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=600&q=80,https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=600&q=80",
                            IsActive = true,
                            Name = "Omega De Ville Prestige",
                            Price = 38000000m,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Certina DS Action, sporty dive watch, ceramic bezel, automatic",
                            Discount = 8m,
                            GalleryImages = "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600&q=80,https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=600&q=80,https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600&q=80",
                            IsActive = true,
                            Name = "Certina DS Action",
                            Price = 9500000m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hamilton Jazzmaster, American spirit, automatic, exhibition caseback",
                            Discount = 0m,
                            GalleryImages = "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=600&q=80,https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&q=80,https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=600&q=80",
                            IsActive = true,
                            Name = "Hamilton Jazzmaster",
                            Price = 14000000m,
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mido Baroncelli, elegant dress watch, automatic, slim profile",
                            Discount = 12m,
                            GalleryImages = "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&q=80,https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&q=80,https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&q=80",
                            IsActive = true,
                            Name = "Mido Baroncelli",
                            Price = 11200000m,
                            StockQuantity = 11
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rado Captain Cook, iconic dive watch, ceramic case, automatic",
                            Discount = 0m,
                            GalleryImages = "https://images.unsplash.com/photo-1619134778706-7015533a6150?w=600&q=80,https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&q=80,https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1619134778706-7015533a6150?w=600&q=80",
                            IsActive = true,
                            Name = "Rado Captain Cook",
                            Price = 24500000m,
                            StockQuantity = 6
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Oris Big Crown Pointer Date, pilot watch, bronze case, automatic",
                            Discount = 0m,
                            GalleryImages = "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&q=80,https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=600&q=80,https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&q=80",
                            IsActive = true,
                            Name = "Oris Big Crown",
                            Price = 29000000m,
                            StockQuantity = 3
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gucci G-Timeless, ladies luxury watch, interlocking G motif",
                            Discount = 20m,
                            GalleryImages = "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=600&q=80,https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=600&q=80,https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=600&q=80",
                            IsActive = true,
                            Name = "Gucci G-Timeless",
                            Price = 18000000m,
                            StockQuantity = 14
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chopard Happy Sport, ladies luxury watch, moving diamonds, steel bracelet",
                            Discount = 0m,
                            GalleryImages = "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=600&q=80,https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=600&q=80,https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=600&q=80",
                            IsActive = true,
                            Name = "Chopard Happy Sport",
                            Price = 42000000m,
                            StockQuantity = 4
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tissot Gentleman couple set, matching elegant design, automatic",
                            Discount = 10m,
                            GalleryImages = "https://images.unsplash.com/photo-1548171915-e79a380a2a4b?w=600&q=80,https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&q=80,https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1548171915-e79a380a2a4b?w=600&q=80",
                            IsActive = true,
                            Name = "Tissot Couple Gentleman",
                            Price = 9200000m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Seiko Presage couple set, Japanese craftsmanship, automatic, enamel dial",
                            Discount = 5m,
                            GalleryImages = "https://images.unsplash.com/photo-1548171915-e79a380a2a4b?w=600&q=80,https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=600&q=80,https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1548171915-e79a380a2a4b?w=600&q=80",
                            IsActive = true,
                            Name = "Seiko Presage Couple",
                            Price = 13400000m,
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Citizen Eco-Drive Promaster, dive watch, light-powered, 200m water resistant",
                            Discount = 0m,
                            GalleryImages = "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600&q=80,https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&q=80,https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600&q=80",
                            IsActive = true,
                            Name = "Citizen Eco-Drive Promaster",
                            Price = 6800000m,
                            StockQuantity = 19
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Longines Conquest Classic, sporty elegance, automatic, 30 bar water resistant",
                            Discount = 0m,
                            GalleryImages = "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=600&q=80,https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&q=80,https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&q=80",
                            ImageUrl = "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=600&q=80",
                            IsActive = true,
                            Name = "Longines Conquest Classic",
                            Price = 19500000m,
                            StockQuantity = 8
                        });
                });

            modelBuilder.Entity("MyProject.Models.SessionVersion", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Key");

                    b.ToTable("SessionVersions", (string)null);
                });

            modelBuilder.Entity("MyProject.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Admin Street, Ho Chi Minh City",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@chronostore.com",
                            FullName = "Admin User",
                            IsActive = true,
                            PasswordHash = "$2a$11$OSNEsLOiiRlpR16p5REbQ.IJWmO/wEXf2nlnsCzv67erHGG0JTJcO",
                            Phone = "0901234567",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Staff Street, Ha Noi",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "staff@chronostore.com",
                            FullName = "Staff User",
                            IsActive = true,
                            PasswordHash = "$2a$11$Lbx80/c219pWcGcSC7kOoukGOB5RCDmD5CiD0mEyQSxfeZhSVaJDq",
                            Phone = "0902345678",
                            Role = "Staff"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Customer Street, Da Nang",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "customer@chronostore.com",
                            FullName = "Customer User",
                            IsActive = true,
                            PasswordHash = "$2a$11$7tLj7ZFD6MNpmBJcl/3LwOWDuNQ3STxtYRs/GejIF2jyeXFWxdYdm",
                            Phone = "0903456789",
                            Role = "Customer"
                        });
                });

            modelBuilder.Entity("MyProject.Models.Order", b =>
                {
                    b.HasOne("MyProject.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyProject.Models.OrderItem", b =>
                {
                    b.HasOne("MyProject.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyProject.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MyProject.Models.Product", b =>
                {
                    b.HasOne("MyProject.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyProject.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MyProject.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
